"""add battery + signal sensor tables

Two new per-zone sensor metrics for device health:
  * ``analytics_batterysensor`` — battery voltage (V), from LoRaWAN nodes
  * ``analytics_signalsensor``  — RSSI (dBm), from LoRaWAN nodes + Bivocom

Mirrors the Django models ``analytics.BatterySensor`` / ``SignalSensor``
(same ``(id, timestamp, user_id, zone_id, value)`` shape as every other
analytics sensor table). Idempotent ``IF NOT EXISTS`` so re-running on a
DB that already has the tables (created out-of-band via the Django schema
editor on the droplet) is a no-op.

Revision ID: b7f2a4c1d9e3
Revises: 31d37a9a428c
Create Date: 2026-06-07 22:10:00.000000+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op

revision: str = "b7f2a4c1d9e3"
down_revision: Union[str, None] = "31d37a9a428c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_TABLES = ("analytics_batterysensor", "analytics_signalsensor")


def upgrade() -> None:
    for table in _TABLES:
        op.execute(
            f"""
            CREATE TABLE IF NOT EXISTS {table} (
                id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "timestamp" timestamptz NOT NULL,
                user_id   bigint NOT NULL,
                zone_id   bigint NOT NULL,
                value     double precision,
                CONSTRAINT {table}_user_id_fk FOREIGN KEY (user_id)
                    REFERENCES "CustomUser_customuser"(id) DEFERRABLE INITIALLY DEFERRED,
                CONSTRAINT {table}_zone_id_fk FOREIGN KEY (zone_id)
                    REFERENCES analytics_zone(id) DEFERRABLE INITIALLY DEFERRED
            );
            """
        )
        op.execute(
            f"CREATE INDEX IF NOT EXISTS {table}_user_id ON {table} (user_id);"
        )
        op.execute(
            f"CREATE INDEX IF NOT EXISTS {table}_zone_id ON {table} (zone_id);"
        )


def downgrade() -> None:
    for table in _TABLES:
        op.execute(f"DROP TABLE IF EXISTS {table};")
