"""add feedback_bugreport table (in-app "Report an issue")

Stores farmer-web bug reports: the free-text report, an optional Cloudinary
screen-recording URL, and rich client context (route, browser, OS, app
version, ...). Written by agri-api ``apps.feedback`` and surfaced in the admin
back-office via the generic ``/api/admin/db`` CRUD. Idempotent.

Revision ID: d0e1f2a3b4c5
Revises: 00a3976cb808
Create Date: 2026-07-01 12:00:00.000000+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op


revision: str = "d0e1f2a3b4c5"
down_revision: Union[str, None] = "00a3976cb808"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS feedback_bugreport (
            id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            report_type   VARCHAR(20)   NOT NULL DEFAULT 'bug',
            title         VARCHAR(255)  NOT NULL,
            description   TEXT          NOT NULL,
            status        VARCHAR(20)   NOT NULL DEFAULT 'open',
            video_url     VARCHAR(1000),
            user_id       BIGINT,
            user_email    VARCHAR(254)  NOT NULL DEFAULT '',
            page_url      VARCHAR(1000) NOT NULL DEFAULT '',
            route         VARCHAR(255)  NOT NULL DEFAULT '',
            module        VARCHAR(100)  NOT NULL DEFAULT '',
            environment   VARCHAR(50)   NOT NULL DEFAULT '',
            app_version   VARCHAR(50)   NOT NULL DEFAULT '',
            browser       VARCHAR(255)  NOT NULL DEFAULT '',
            os            VARCHAR(100)  NOT NULL DEFAULT '',
            context       JSONB,
            created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
            updated_at    TIMESTAMPTZ,
            CONSTRAINT feedback_bugreport_user_id_fkey
                FOREIGN KEY (user_id) REFERENCES "CustomUser_customuser" (id)
                DEFERRABLE INITIALLY DEFERRED
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS feedback_bugreport_user_id_idx "
        "ON feedback_bugreport (user_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS feedback_bugreport_status_idx "
        "ON feedback_bugreport (status)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS feedback_bugreport")
