"""add custom notification zones + alert notify_sms

Custom notification zones (agrilogy-front #57): a user-owned alert grouping that
is independent of the farm ``analytics_zone`` rows. An alert binds to EITHER a
farm zone (``zone_id``, unchanged) OR a notification zone
(``notification_zone_id``); when bound to a notification zone its data stream is
resolved through ``analytics_notificationzonesensor`` rows, each pointing at a
``(sensor_key, source_zone_id)`` reading stream.

Also adds ``analytics_alert.notify_sms`` so SMS becomes a real per-alert
delivery channel alongside email/WhatsApp.

All statements are idempotent (``IF NOT EXISTS``) so re-running after a Django
``migrate`` is a no-op.

Revision ID: e2f3a4b5c6d7
Revises: d1e2f3a4b5c6
Create Date: 2026-06-25 17:05:00.000000+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op


revision: str = "e2f3a4b5c6d7"
down_revision: Union[str, None] = "d1e2f3a4b5c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS analytics_notificationzone (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(200) NOT NULL,
            description TEXT NOT NULL DEFAULT '',
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            user_id BIGINT NOT NULL
                REFERENCES "CustomUser_customuser" (id)
                DEFERRABLE INITIALLY DEFERRED,
            created_at TIMESTAMPTZ,
            updated_at TIMESTAMPTZ
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS analytics_notificationzone_user_id_idx "
        "ON analytics_notificationzone (user_id)"
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS analytics_notificationzonesensor (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sensor_key VARCHAR(64) NOT NULL,
            label VARCHAR(200),
            notification_zone_id BIGINT NOT NULL
                REFERENCES analytics_notificationzone (id) ON DELETE CASCADE
                DEFERRABLE INITIALLY DEFERRED,
            source_zone_id BIGINT
                REFERENCES analytics_zone (id) ON DELETE SET NULL
                DEFERRABLE INITIALLY DEFERRED
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS analytics_notificationzonesensor_zone_idx "
        "ON analytics_notificationzonesensor (notification_zone_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS analytics_notificationzonesensor_source_idx "
        "ON analytics_notificationzonesensor (source_zone_id)"
    )

    op.execute(
        "ALTER TABLE analytics_alert ADD COLUMN IF NOT EXISTS notification_zone_id "
        "BIGINT REFERENCES analytics_notificationzone (id) ON DELETE SET NULL "
        "DEFERRABLE INITIALLY DEFERRED"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS analytics_alert_notification_zone_id_idx "
        "ON analytics_alert (notification_zone_id)"
    )
    op.execute(
        "ALTER TABLE analytics_alert "
        "ADD COLUMN IF NOT EXISTS notify_sms BOOLEAN NOT NULL DEFAULT FALSE"
    )


def downgrade() -> None:
    op.execute("ALTER TABLE analytics_alert DROP COLUMN IF EXISTS notify_sms")
    op.execute("ALTER TABLE analytics_alert DROP COLUMN IF EXISTS notification_zone_id")
    op.execute("DROP TABLE IF EXISTS analytics_notificationzonesensor")
    op.execute("DROP TABLE IF EXISTS analytics_notificationzone")
