"""absorb the agri-api ensure-script tables into Alembic (15 tables)

The live droplet creates these tables OUTSIDE Alembic via agri-api boot
scripts (back/scripts/ensure_*_tables.py -> docker-entrypoint.sh). This
revision absorbs them into the schema-of-record:

  ensure_admin_tables.py       -> analytics_plan, analytics_subscription,
                                  analytics_invoice, analytics_auditevent,
                                  analytics_systemsetting
  ensure_assistant_tables.py   -> assistant_conversation,
                                  assistant_proactive_notice
  ensure_device_tables.py      -> analytics_device
  ensure_irrigation_tables.py  -> analytics_irrigationprogram,
                                  analytics_outputcommand
  ensure_monitoring_tables.py  -> analytics_taskrun,
                                  analytics_notificationdeliverylog,
                                  analytics_loginevent
  ensure_technician_tables.py  -> analytics_techniciangrant,
                                  analytics_technicianzonegrant
                                  (+ CustomUser_customuser.is_technician)

DDL byte-matches the live droplet schema (pg_dump 2026-07-02): the Django
models declare every relation with ``db_constraint=False``, so there are NO
DB-level foreign keys and no secondary indexes — only PKs, unique constraints
and one CHECK. Everything is ``IF NOT EXISTS`` (checkfirst semantics) so
existing droplet DBs converge without error. Idempotent.

Revision ID: e5f6a7b8c9d0
Revises: d0e1f2a3b4c5
Create Date: 2026-07-02 00:45:00.000000+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op


revision: str = "e5f6a7b8c9d0"
down_revision: Union[str, None] = "d0e1f2a3b4c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


TABLES_DDL = (
    # --- billing (ensure_admin_tables.py) --------------------------------
    """
    CREATE TABLE IF NOT EXISTS analytics_plan (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name        VARCHAR(100) NOT NULL,
        price_dh    DOUBLE PRECISION NOT NULL,
        "interval"  VARCHAR(16)  NOT NULL,
        features    JSONB        NOT NULL,
        is_active   BOOLEAN      NOT NULL,
        created_at  TIMESTAMPTZ
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS analytics_subscription (
        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id      BIGINT      NOT NULL,
        plan_id      BIGINT,
        status       VARCHAR(16) NOT NULL,
        period_start DATE,
        period_end   DATE,
        created_at   TIMESTAMPTZ
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS analytics_invoice (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        subscription_id BIGINT           NOT NULL,
        amount_dh       DOUBLE PRECISION NOT NULL,
        status          VARCHAR(16)      NOT NULL,
        issued_at       TIMESTAMPTZ,
        paid_at         TIMESTAMPTZ
    )
    """,
    # --- audit / settings (ensure_admin_tables.py) ------------------------
    """
    CREATE TABLE IF NOT EXISTS analytics_auditevent (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        actor_id    BIGINT,
        action      VARCHAR(64) NOT NULL,
        target_type VARCHAR(64) NOT NULL,
        target_id   VARCHAR(64) NOT NULL,
        changes     JSONB       NOT NULL,
        created_at  TIMESTAMPTZ
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS analytics_systemsetting (
        id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        key        VARCHAR(100) NOT NULL,
        value      JSONB        NOT NULL,
        category   VARCHAR(64)  NOT NULL,
        updated_at TIMESTAMPTZ,
        CONSTRAINT analytics_systemsetting_key_key UNIQUE (key)
    )
    """,
    # --- device registry (ensure_device_tables.py) ------------------------
    """
    CREATE TABLE IF NOT EXISTS analytics_device (
        id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id              BIGINT       NOT NULL,
        zone_id              BIGINT,
        device_type          VARCHAR(20)  NOT NULL,
        serial               VARCHAR(128) NOT NULL,
        name                 VARCHAR(120) NOT NULL,
        is_active            BOOLEAN      NOT NULL,
        last_health_notified TIMESTAMPTZ,
        created_at           TIMESTAMPTZ,
        CONSTRAINT analytics_device_serial_key UNIQUE (serial)
    )
    """,
    # --- irrigation automation (ensure_irrigation_tables.py) --------------
    """
    CREATE TABLE IF NOT EXISTS analytics_irrigationprogram (
        id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id          BIGINT       NOT NULL,
        zone_id          BIGINT       NOT NULL,
        name             VARCHAR(120) NOT NULL,
        enabled          BOOLEAN      NOT NULL,
        start_time       TIME         NOT NULL,
        weekdays         VARCHAR(32)  NOT NULL,
        duration_min     INTEGER,
        target_volume_m3 DOUBLE PRECISION,
        last_run_at      TIMESTAMPTZ,
        created_at       TIMESTAMPTZ,
        updated_at       TIMESTAMPTZ,
        CONSTRAINT analytics_irrigationprogram_duration_min_check
            CHECK (duration_min >= 0)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS analytics_outputcommand (
        id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id       BIGINT       NOT NULL,
        zone_id       BIGINT       NOT NULL,
        device_id     BIGINT,
        action        VARCHAR(8)   NOT NULL,
        source        VARCHAR(12)  NOT NULL,
        status        VARCHAR(12)  NOT NULL,
        detail        VARCHAR(255) NOT NULL,
        created_at    TIMESTAMPTZ,
        dispatched_at TIMESTAMPTZ
    )
    """,
    # --- monitoring (ensure_monitoring_tables.py) --------------------------
    """
    CREATE TABLE IF NOT EXISTS analytics_taskrun (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        task_name   VARCHAR(128) NOT NULL,
        status      VARCHAR(16)  NOT NULL,
        started_at  TIMESTAMPTZ,
        finished_at TIMESTAMPTZ,
        runtime_ms  INTEGER,
        result      JSONB        NOT NULL,
        error       TEXT         NOT NULL,
        created_at  TIMESTAMPTZ
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS analytics_notificationdeliverylog (
        id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        channel    VARCHAR(16)  NOT NULL,
        kind       VARCHAR(24)  NOT NULL,
        recipient  VARCHAR(255) NOT NULL,
        user_id    BIGINT,
        status     VARCHAR(12)  NOT NULL,
        error      TEXT         NOT NULL,
        created_at TIMESTAMPTZ
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS analytics_loginevent (
        id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username   VARCHAR(150) NOT NULL,
        user_id    BIGINT,
        success    BOOLEAN      NOT NULL,
        ip         VARCHAR(64)  NOT NULL,
        user_agent VARCHAR(255) NOT NULL,
        created_at TIMESTAMPTZ
    )
    """,
    # --- technician RBAC (ensure_technician_tables.py) ---------------------
    """
    CREATE TABLE IF NOT EXISTS analytics_techniciangrant (
        id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        technician_id BIGINT  NOT NULL,
        owner_id      BIGINT  NOT NULL,
        is_active     BOOLEAN NOT NULL,
        created_at    TIMESTAMPTZ,
        CONSTRAINT uniq_technician_owner UNIQUE (technician_id, owner_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS analytics_technicianzonegrant (
        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        grant_id       BIGINT NOT NULL,
        zone_id        BIGINT NOT NULL,
        allowed_graphs JSONB  NOT NULL,
        CONSTRAINT uniq_grant_zone UNIQUE (grant_id, zone_id)
    )
    """,
    # --- assistant (ensure_assistant_tables.py) ----------------------------
    """
    CREATE TABLE IF NOT EXISTS assistant_conversation (
        id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id    BIGINT       NOT NULL,
        client_id  VARCHAR(64)  NOT NULL,
        title      VARCHAR(200) NOT NULL,
        messages   JSONB        NOT NULL,
        created_at TIMESTAMPTZ  NOT NULL,
        updated_at TIMESTAMPTZ  NOT NULL,
        CONSTRAINT uniq_user_client_conversation UNIQUE (user_id, client_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS assistant_proactive_notice (
        id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id   BIGINT NOT NULL,
        last_sent TIMESTAMPTZ,
        CONSTRAINT assistant_proactive_notice_user_id_key UNIQUE (user_id)
    )
    """,
)

TABLE_NAMES = (
    "analytics_plan",
    "analytics_subscription",
    "analytics_invoice",
    "analytics_auditevent",
    "analytics_systemsetting",
    "analytics_device",
    "analytics_irrigationprogram",
    "analytics_outputcommand",
    "analytics_taskrun",
    "analytics_notificationdeliverylog",
    "analytics_loginevent",
    "analytics_techniciangrant",
    "analytics_technicianzonegrant",
    "assistant_conversation",
    "assistant_proactive_notice",
)


def upgrade() -> None:
    for ddl in TABLES_DDL:
        op.execute(ddl)

    # ensure_technician_tables.py also adds CustomUser.is_technician. Live has
    # it NOT NULL with no DB default (Django keeps the default in the app
    # layer), so backfill via a transient DEFAULT then drop it — a no-op on
    # DBs where the column already exists.
    op.execute(
        'ALTER TABLE "CustomUser_customuser" '
        "ADD COLUMN IF NOT EXISTS is_technician BOOLEAN NOT NULL DEFAULT false"
    )
    op.execute(
        'ALTER TABLE "CustomUser_customuser" '
        "ALTER COLUMN is_technician DROP DEFAULT"
    )


def downgrade() -> None:
    op.execute(
        'ALTER TABLE "CustomUser_customuser" DROP COLUMN IF EXISTS is_technician'
    )
    for table in reversed(TABLE_NAMES):
        op.execute(f"DROP TABLE IF EXISTS {table}")
