"""add alert-event and irrigation-decision history tables

Storage of record for the historical report (agri-api RPT-1 / #399, P1):

* ``analytics_alertevent`` — one row per alert firing (rule + zone + device,
  observed value vs. the threshold it violated), append-only. Today only the
  LAST firing survives, on ``analytics_alert.last_triggered_at``.
* ``analytics_irrigationdecision`` — one row per computed recommendation: the
  ``agri.core.agronomy.IrrigationDecision`` outcome plus the water-balance /
  ET inputs it was derived from. Today the result is discarded once the
  notification email is rendered.

Both are indexed for the report query shape "date range + zone". No writer
ships here — agri-core / agri-api populate them in their own tickets. DDL is
idempotent; ``downgrade()`` drops both tables.

Revision ID: e7a1c3d5b209
Revises: b33c23723140
Create Date: 2026-07-22 10:00:00.000000+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op


revision: str = "e7a1c3d5b209"
down_revision: Union[str, None] = "b33c23723140"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ------------------------------------------------------------------
    # analytics_alertevent — history of alert firings.
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS analytics_alertevent (
            id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            triggered_at         TIMESTAMPTZ      NOT NULL DEFAULT now(),
            alert_id             BIGINT,
            user_id              BIGINT           NOT NULL,
            zone_id              BIGINT,
            notification_zone_id BIGINT,
            device_id            BIGINT,
            sensor_key           VARCHAR(64)      NOT NULL,
            alert_name           VARCHAR(200)     NOT NULL DEFAULT '',
            condition            VARCHAR(1)       NOT NULL,
            threshold_value      DOUBLE PRECISION NOT NULL,
            observed_value       DOUBLE PRECISION NOT NULL,
            reading_at           TIMESTAMPTZ,
            unit                 VARCHAR(32)      NOT NULL DEFAULT '',
            notified_channels    VARCHAR(64)      NOT NULL DEFAULT '',
            context              JSONB,
            created_at           TIMESTAMPTZ      NOT NULL DEFAULT now(),
            CONSTRAINT analytics_alertevent_alert_id_fkey
                FOREIGN KEY (alert_id) REFERENCES analytics_alert (id)
                ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT analytics_alertevent_user_id_fkey
                FOREIGN KEY (user_id) REFERENCES "CustomUser_customuser" (id)
                DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT analytics_alertevent_zone_id_fkey
                FOREIGN KEY (zone_id) REFERENCES analytics_zone (id)
                ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT analytics_alertevent_notification_zone_id_fkey
                FOREIGN KEY (notification_zone_id)
                REFERENCES analytics_notificationzone (id)
                ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS analytics_alertevent_zone_triggered_idx "
        "ON analytics_alertevent (zone_id, triggered_at)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS analytics_alertevent_user_triggered_idx "
        "ON analytics_alertevent (user_id, triggered_at)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS analytics_alertevent_triggered_at_idx "
        "ON analytics_alertevent (triggered_at)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS analytics_alertevent_alert_id_idx "
        "ON analytics_alertevent (alert_id)"
    )

    # ------------------------------------------------------------------
    # analytics_irrigationdecision — history of computed recommendations.
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS analytics_irrigationdecision (
            id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            decided_at                TIMESTAMPTZ      NOT NULL DEFAULT now(),
            decision_date             DATE,
            user_id                   BIGINT           NOT NULL,
            zone_id                   BIGINT           NOT NULL,
            source                    VARCHAR(20)      NOT NULL DEFAULT '',
            irrigate                  BOOLEAN          NOT NULL,
            reason                    VARCHAR(32)      NOT NULL,
            net_mm                    DOUBLE PRECISION NOT NULL DEFAULT 0,
            gross_mm                  DOUBLE PRECISION NOT NULL DEFAULT 0,
            volume_m3                 DOUBLE PRECISION NOT NULL DEFAULT 0,
            duration_hr               DOUBLE PRECISION NOT NULL DEFAULT 0,
            morning_volume_m3         DOUBLE PRECISION,
            evening_volume_m3         DOUBLE PRECISION,
            capped_to_daily_max       BOOLEAN          NOT NULL DEFAULT false,
            summary                   TEXT             NOT NULL DEFAULT '',
            dr_today_mm               DOUBLE PRECISION,
            raw_mm                    DOUBLE PRECISION,
            taw_mm                    DOUBLE PRECISION,
            et0_mm                    DOUBLE PRECISION,
            kc_used                   DOUBLE PRECISION,
            etc_mm                    DOUBLE PRECISION,
            soil_moisture_pct         DOUBLE PRECISION,
            critical_moisture_pct     DOUBLE PRECISION,
            precipitation_forecast_mm DOUBLE PRECISION NOT NULL DEFAULT 0,
            effective_rainfall_mm     DOUBLE PRECISION,
            zone_area_m2              DOUBLE PRECISION,
            flow_rate_m3h             DOUBLE PRECISION,
            max_water_per_day_m3      DOUBLE PRECISION,
            irrigation_efficiency     DOUBLE PRECISION,
            kr                        DOUBLE PRECISION,
            context                   JSONB,
            created_at                TIMESTAMPTZ      NOT NULL DEFAULT now(),
            CONSTRAINT analytics_irrigationdecision_user_id_fkey
                FOREIGN KEY (user_id) REFERENCES "CustomUser_customuser" (id)
                DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT analytics_irrigationdecision_zone_id_fkey
                FOREIGN KEY (zone_id) REFERENCES analytics_zone (id)
                ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS analytics_irrigationdecision_zone_decided_idx "
        "ON analytics_irrigationdecision (zone_id, decided_at)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS analytics_irrigationdecision_user_decided_idx "
        "ON analytics_irrigationdecision (user_id, decided_at)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS analytics_irrigationdecision_decided_at_idx "
        "ON analytics_irrigationdecision (decided_at)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS analytics_irrigationdecision")
    op.execute("DROP TABLE IF EXISTS analytics_alertevent")
