"""add sensor groups + per-sensor calibration

Two farmer-facing features, one schema change:

* ``analytics_sensorgroup`` / ``analytics_sensorgroupsensor`` (agri-web #64) —
  server-side, user-owned sensor groups replacing the browser-local grouping.
  The owner is the user account (one farm per account); a group may span zones.
* ``analytics_sensorcalibration`` (agri-web #67) — affine correction
  ``real = raw * scale_a + offset_b`` plus the target ``unit``, one row per
  sensor stream. Storage only; the transform lands later in agri-core.

A sensor stream is identified by ``(device_id, sensor_key)`` in BOTH features:
``device_id`` is the soft FK to the Django-managed ``analytics_device`` carried
by every reading row (``agri.db.base.HasDeviceId``) and ``sensor_key`` is the
canonical vocabulary from ``agri.core`` selecting the reading table. No DB-level
FK on ``device_id``, matching the readings and ``analytics_devicesensor``.

Idempotent DDL so it is safe to re-run against a partially-provisioned DB.

Revision ID: f4b6d2e8c1a9
Revises: e7a1c3d5b209
Create Date: 2026-07-22 10:00:00.000000+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op


revision: str = "f4b6d2e8c1a9"
down_revision: Union[str, None] = "e7a1c3d5b209"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ---------------------------------------------------------------- groups
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS analytics_sensorgroup (
            id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name          VARCHAR(200) NOT NULL,
            description   TEXT         NOT NULL DEFAULT '',
            user_id       BIGINT       NOT NULL,
            display_order INTEGER      NOT NULL DEFAULT 0,
            is_active     BOOLEAN      NOT NULL DEFAULT true,
            created_at    TIMESTAMPTZ,
            updated_at    TIMESTAMPTZ,
            CONSTRAINT analytics_sensorgroup_pkey PRIMARY KEY (id),
            CONSTRAINT analytics_sensorgroup_user_name_uniq
                UNIQUE (user_id, name),
            CONSTRAINT analytics_sensorgroup_user_id_fk
                FOREIGN KEY (user_id) REFERENCES "CustomUser_customuser" (id)
                DEFERRABLE INITIALLY DEFERRED
        )
        """
    )
    # "all groups for a user" — the group-list query shape.
    op.execute(
        "CREATE INDEX IF NOT EXISTS analytics_sensorgroup_user_id_idx "
        "ON analytics_sensorgroup (user_id)"
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS analytics_sensorgroupsensor (
            id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            group_id      BIGINT      NOT NULL,
            device_id     BIGINT      NOT NULL,
            sensor_key    VARCHAR(64) NOT NULL,
            label         VARCHAR(200),
            zone_id       BIGINT,
            display_order INTEGER     NOT NULL DEFAULT 0,
            created_at    TIMESTAMPTZ,
            CONSTRAINT analytics_sensorgroupsensor_pkey PRIMARY KEY (id),
            CONSTRAINT analytics_sensorgroupsensor_group_sensor_uniq
                UNIQUE (group_id, device_id, sensor_key),
            CONSTRAINT analytics_sensorgroupsensor_group_id_fk
                FOREIGN KEY (group_id) REFERENCES analytics_sensorgroup (id)
                ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT analytics_sensorgroupsensor_zone_id_fk
                FOREIGN KEY (zone_id) REFERENCES analytics_zone (id)
                ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
        )
        """
    )
    # "...with their sensors" — the join side of the group-list query.
    op.execute(
        "CREATE INDEX IF NOT EXISTS analytics_sensorgroupsensor_group_idx "
        "ON analytics_sensorgroupsensor (group_id)"
    )
    # "which groups contain this sensor" — reverse lookup on the stream key.
    op.execute(
        "CREATE INDEX IF NOT EXISTS analytics_sensorgroupsensor_sensor_idx "
        "ON analytics_sensorgroupsensor (device_id, sensor_key)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS analytics_sensorgroupsensor_zone_idx "
        "ON analytics_sensorgroupsensor (zone_id)"
    )

    # ----------------------------------------------------------- calibration
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS analytics_sensorcalibration (
            id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            device_id  BIGINT           NOT NULL,
            sensor_key VARCHAR(64)      NOT NULL,
            scale_a    DOUBLE PRECISION NOT NULL DEFAULT 1.0,
            offset_b   DOUBLE PRECISION NOT NULL DEFAULT 0.0,
            unit       VARCHAR(32)      NOT NULL DEFAULT '',
            is_active  BOOLEAN          NOT NULL DEFAULT true,
            note       TEXT             NOT NULL DEFAULT '',
            created_at TIMESTAMPTZ,
            updated_at TIMESTAMPTZ,
            CONSTRAINT analytics_sensorcalibration_pkey PRIMARY KEY (id),
            CONSTRAINT analytics_sensorcalibration_sensor_uniq
                UNIQUE (device_id, sensor_key)
        )
        """
    )
    # "calibration for a given sensor" is served by the unique constraint's
    # index; this one covers "all calibrations of a device" (device detail).
    op.execute(
        "CREATE INDEX IF NOT EXISTS analytics_sensorcalibration_device_idx "
        "ON analytics_sensorcalibration (device_id)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS analytics_sensorcalibration")
    # Membership first: it holds the FK onto the group table.
    op.execute("DROP TABLE IF EXISTS analytics_sensorgroupsensor")
    op.execute("DROP TABLE IF EXISTS analytics_sensorgroup")
